CREATE TABLE IF NOT EXISTS logs (
  id     BIGINT    AUTO_INCREMENT PRIMARY KEY,
  userId VARCHAR(36) NOT NULL,
  apikey VARCHAR(36) NOT NULL,
  hash   VARCHAR(40) NOT NULL,
  ts     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `logs_apikeys` FOREIGN KEY (`apikey`) REFERENCES `apikeys` (`apikey`)
)